remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme


show_downloads: true

title: The FairVidSum Dataset
description: A Dataset for Fair Video Summarization


github:
  zip_url: https://drive.google.com/file/d/1Y83yaeLv8VSpBjcFJyWoHa6zzEq49dCO/view
  another_url: https://drive.google.com/file/d/1Y83yaeLv8VSpBjcFJyWoHa6zzEq49dCO/view
